name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Create install coverage
      run: python -m pip install coverage
    - name: run the coverage
      run: python -m coverage run -m unittest discover
